---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda

dependencies:
  # renovate: datasource=conda depName=bioconda/gatk4
  - bioconda::gatk4=4.6.1.0
  - bioconda::gcnvkernel=0.9
  - bioconda::htslib=1.21
  - bioconda::samtools=1.21
