sudo: required

language: java

jdk: openjdk8

node_js: "node"

services:
  - docker

env:
  global:
    - NXF_VER=0.27.0 SGT_VER=2.4.2
  matrix:
    - PROFILE=singularity TEST=TOOLS          TOOL_INSTALL=all
    - PROFILE=singularity TEST=MANTA          TOOL_INSTALL=all
    - PROFILE=docker      TEST=MANTA          TOOL_INSTALL=nextflow
    - PROFILE=docker      TEST=TOOLS          TOOL_INSTALL=nextflow
    - PROFILE=docker      TEST=ANNOTATEVEP    TOOL_INSTALL=nextflow
    - PROFILE=singularity TEST=ANNOTATESNPEFF TOOL_INSTALL=all
    - PROFILE=singularity TEST=STEP           TOOL_INSTALL=all
    - PROFILE=singularity TEST=GERMLINE       TOOL_INSTALL=all
    - PROFILE=singularity TEST=DIR            TOOL_INSTALL=all
    - PROFILE=docker      TEST=ANNOTATESNPEFF TOOL_INSTALL=nextflow
    - PROFILE=docker      TEST=STEP           TOOL_INSTALL=nextflow
    - PROFILE=docker      TEST=GERMLINE       TOOL_INSTALL=nextflow
    - PROFILE=docker      TEST=DIR            TOOL_INSTALL=nextflow

install: # Install Nextflow (and Singularity if needed)
  - "./scripts/install.sh --tool $TOOL_INSTALL"
  - "travis_retry ./scripts/containers.sh --profile $PROFILE --test $TEST"

before_script: # Build references when needed
  - "./scripts/test.sh --profile $PROFILE --test $TEST --build"

script:
  - "./scripts/test.sh --profile $PROFILE --test $TEST"
