# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-sarek-2.5.2
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - ascat=2.5.2
  - bcftools=1.9
  - beagle=5.1
  - bwa=0.7.17
  - cancerit-allelecount=4.0.2
  - control-freec=11.4
  - ensembl-vep=95.2
  - fastqc=0.11.8
  - freebayes=1.2.0
  - gatk4=4.1.2.0
  - genesplicer=1.0
  - htslib=1.9
  - manta=1.5.0
  - mapdamage2
  - multiqc=1.7
  - perl-sanger-cgp-battenberg=1.4.1
  - platypus-variant=0.8.1.2
  - qualimap=2.2.2b
  - r-sequenza=3.0.0
  - samtools=1.9
  - skewer=0.2.2
  - snpeff=4.3.1t
  - strelka=2.9.10
  - tiddit=2.7.1
  - vcfanno=0.3.1
  - vcftools=0.1.16
