# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: sarek-2.3
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  # conda-forge packages
  - r-rcolorbrewer=1.1
  - r-base=3.5.1
  # bioconda packages
  - bcftools=1.9
  - bioconductor-rtracklayer=1.42.1
  - bwa=0.7.17
  - cancerit-allelecount=2.1.2
  - control-freec=11.4
  - ensembl-vep=96.0
  - fastqc=0.11.8
  - freebayes=1.2.0
  - gatk4=4.1.1.0
  - genesplicer=1.0
  - htslib=1.9
  - igvtools=2.3.93
  - manta=1.5.0
  - multiqc=1.7
  - qualimap=2.2.2b
  - samtools=1.9
  - snpeff=4.3.1t
  - strelka=2.9.10
  - vcfanno=0.3.1
  - vcftools=0.1.16
