---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # renovate: datasource=conda depName=bioconda/gatk4
  - bioconda::gatk4=4.6.1.0
  # renovate: datasource=conda depName=bioconda/gcnvkernel
  - bioconda::gcnvkernel=0.9
