# You can use this file to create a conda environment for this module:
#   conda env create -f environment.yml
name: nf-core-vep-106.1
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconda::ensembl-vep=106.1
