name: narfmap_align
channels:
  - conda-forge
  - bioconda
dependencies:
  # renovate: datasource=conda depName=bioconda/narfmap
  - narfmap=1.4.2
  # renovate: datasource=conda depName=bioconda/samtools
  - samtools=1.20
  - pigz=2.8
