---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  # renovate: datasource=conda depName=bioconda/htslib
  - bioconda::htslib=1.22.1
  # renovate: datasource=conda depName=bioconda/bcftools
  - bioconda::bcftools=1.22
