name: nf-core AWS test
# This workflow can be triggered manually with the GitHub actions workflow dispatch button.
# It runs the -profile 'test' on AWS batch

on:
  release:
    types: [created]
  workflow_dispatch:
    inputs:
      profiletest:
        description: "Trigger profile tests (smaller) on AWS"
        type: boolean
        default: true
      somatic:
        description: "Trigger somatic full test on AWS"
        type: boolean
        default: false
      germline:
        description: "Trigger germline full test on AWS"
        type: boolean
        default: false

jobs:
  trigger-profile-test:
    name: Run AWS tests
    if: ( github.repository == 'nf-core/sarek' ) && ( github.event_name != 'workflow_dispatch' || inputs.profiletest )
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Tower CLI tool action
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/sarek/work-${{ github.sha }}
          parameters: |
            {
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/sarek/results-test-${{ github.sha }}"
            }
          profiles: test
      - uses: actions/upload-artifact@v3
        with:
          name: tower-profiletest-log
          path: |
            tower_action_*.log
            tower_action_*.json

  trigger-full-test-somatic:
    name: Run AWS full tests
    if: ${{ ( github.repository == 'nf-core/sarek' ) || ( github.event_name != 'workflow_dispatch' || inputs.somatic ) }}
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Tower CLI tool action
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/sarek/work-${{ github.sha }}/somatic_test
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/sarek/results-${{ github.sha }}/somatic_test"
            }
          profiles: test_full

      - uses: actions/upload-artifact@v3
        with:
          name: tower-full-somatic-log
          path: |
            tower_action_*.log
            tower_action_*.json

  trigger-full-test-germline:
    name: Run AWS full tests
    if: ${{ ( github.repository == 'nf-core/sarek' ) || ( github.event_name != 'workflow_dispatch' || inputs.germline ) }}
    runs-on: ubuntu-latest
    steps:
      # Launch workflow using Tower CLI tool action
      - name: Launch workflow via tower
        uses: seqeralabs/action-tower-launch@v2
        with:
          workspace_id: ${{ secrets.TOWER_WORKSPACE_ID }}
          access_token: ${{ secrets.TOWER_ACCESS_TOKEN }}
          compute_env: ${{ secrets.TOWER_COMPUTE_ENV }}
          revision: ${{ github.sha }}
          workdir: s3://${{ secrets.AWS_S3_BUCKET }}/work/sarek/work-${{ github.sha }}/germline_test
          parameters: |
            {
              "hook_url": "${{ secrets.MEGATESTS_ALERTS_SLACK_HOOK_URL }}",
              "outdir": "s3://${{ secrets.AWS_S3_BUCKET }}/sarek/results-${{ github.sha }}/germline_test"
            }
          profiles: test_full_germline
      - uses: actions/upload-artifact@v3
        with:
          name: tower-full-germline-log
          path: tower_action_*.log
