name: nf-core aws test
# This workflow is triggered on pushes and PRs to the repository.
# It runs the -profile 'test' on AWS batch
on:
  push:
  pull_request:
  release:
    types: [published]

jobs:
    Awstest:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ['ubuntu-latest']
                python-version: ['3.7']
        steps:
        - uses: goanpeca/setup-miniconda@v1
          with:
            auto-update-conda: true
            python-version: ${{ matrix.python-version }}
        - name: Install aws client
          run: conda install -c conda-forge awscli
        - name: Start AWS batch job
          env:
            AWS_ACCESS_KEY_ID: ${{secrets.AWS_KEY_ID}}
            AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_KEY_SECRET}}
            TOWER_ACCESS_TOKEN: ${{secrets.TOWER_ACCESS_TOKEN}}
          run: |
            aws batch submit-job --region eu-west-1 --job-name nf-core-rnaseq --job-queue 'default-8b3836e0-5eda-11ea-96e5-0a2c3f6a2a32' --job-definition nextflow --container-overrides command=nf-core/sarek,"-profile test -with-tower"
